INSERT INTO teams (name, coach) VALUES ('ateam', 'a');
INSERT INTO teams (name, coach) VALUES ('ryan_team', 'ryan');
INSERT INTO teams (name, coach) VALUES ('bob_team', 'bob');
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('ateam', 'bob_team', 2, 0);
INSERT INTO teams (name, coach) VALUES ('joe_team', 'joe');
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('joe_team', 'ateam', 2, 2);
INSERT INTO teams (name, coach) VALUES ('pal_team', 'pal');
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('pal_team', 'ateam', 4, 1);
INSERT INTO teams (name, coach) VALUES ('team1', 'coach1');
INSERT INTO teams (name, coach) VALUES ('team2', 'coach2');
INSERT INTO teams (name, coach) VALUES ('team3', 'coach3');
INSERT INTO teams (name, coach) VALUES ('team4', 'coach4');
INSERT INTO teams (name, coach) VALUES ('team5', 'coach5');
INSERT INTO teams (name, coach) VALUES ('team6', 'coach6');
INSERT INTO teams (name, coach) VALUES ('team7', 'coach7');
INSERT INTO teams (name, coach) VALUES ('team8', 'coach8');
INSERT INTO teams (name, coach) VALUES ('team9', 'coach9');
INSERT INTO teams (name, coach) VALUES ('team10', 'coach10');
INSERT INTO teams (name, coach) VALUES ('team11', 'coach11');
INSERT INTO teams (name, coach) VALUES ('team12', 'coach12');
INSERT INTO teams (name, coach) VALUES ('team13', 'coach13');
INSERT INTO teams (name, coach) VALUES ('team14', 'coach14');
INSERT INTO teams (name, coach) VALUES ('team15', 'coach15');
INSERT INTO teams (name, coach) VALUES ('team16', 'coach16');
INSERT INTO teams (name, coach) VALUES ('team17', 'coach17');
INSERT INTO teams (name, coach) VALUES ('team18', 'coach18');
INSERT INTO teams (name, coach) VALUES ('team19', 'coach19');
INSERT INTO teams (name, coach) VALUES ('team20', 'coach20');
INSERT INTO teams (name, coach) VALUES ('team21', 'coach21');
INSERT INTO teams (name, coach) VALUES ('team22', 'coach22');
INSERT INTO teams (name, coach) VALUES ('team23', 'coach23');
INSERT INTO teams (name, coach) VALUES ('team24', 'coach24');
INSERT INTO teams (name, coach) VALUES ('team25', 'coach25');
INSERT INTO teams (name, coach) VALUES ('team26', 'coach26');
INSERT INTO teams (name, coach) VALUES ('team27', 'coach27');
INSERT INTO teams (name, coach) VALUES ('team28', 'coach28');
INSERT INTO teams (name, coach) VALUES ('team29', 'coach29');
INSERT INTO teams (name, coach) VALUES ('team30', 'coach30');
INSERT INTO teams (name, coach) VALUES ('team31', 'coach31');
INSERT INTO teams (name, coach) VALUES ('team32', 'coach32');
INSERT INTO teams (name, coach) VALUES ('team33', 'coach33');
INSERT INTO teams (name, coach) VALUES ('team34', 'coach34');
INSERT INTO teams (name, coach) VALUES ('team35', 'coach35');
INSERT INTO teams (name, coach) VALUES ('team36', 'coach36');
INSERT INTO teams (name, coach) VALUES ('team37', 'coach37');
INSERT INTO teams (name, coach) VALUES ('team38', 'coach38');
INSERT INTO teams (name, coach) VALUES ('team39', 'coach39');
INSERT INTO teams (name, coach) VALUES ('team40', 'coach40');
INSERT INTO teams (name, coach) VALUES ('team41', 'coach41');
INSERT INTO teams (name, coach) VALUES ('team42', 'coach42');
INSERT INTO teams (name, coach) VALUES ('team43', 'coach43');
INSERT INTO teams (name, coach) VALUES ('team44', 'coach44');
INSERT INTO teams (name, coach) VALUES ('team45', 'coach45');
INSERT INTO teams (name, coach) VALUES ('team46', 'coach46');
INSERT INTO teams (name, coach) VALUES ('team47', 'coach47');
INSERT INTO teams (name, coach) VALUES ('team48', 'coach48');
INSERT INTO teams (name, coach) VALUES ('team49', 'coach49');
INSERT INTO teams (name, coach) VALUES ('team50', 'coach50');
INSERT INTO teams (name, coach) VALUES ('team51', 'coach51');
INSERT INTO teams (name, coach) VALUES ('team52', 'coach52');
INSERT INTO teams (name, coach) VALUES ('team53', 'coach53');
INSERT INTO teams (name, coach) VALUES ('team54', 'coach54');
INSERT INTO teams (name, coach) VALUES ('team55', 'coach55');
INSERT INTO teams (name, coach) VALUES ('team56', 'coach56');
INSERT INTO teams (name, coach) VALUES ('team57', 'coach57');
INSERT INTO teams (name, coach) VALUES ('team58', 'coach58');
INSERT INTO teams (name, coach) VALUES ('team59', 'coach59');
INSERT INTO teams (name, coach) VALUES ('team60', 'coach60');
INSERT INTO teams (name, coach) VALUES ('team61', 'coach61');
INSERT INTO teams (name, coach) VALUES ('team62', 'coach62');
INSERT INTO teams (name, coach) VALUES ('team63', 'coach63');
INSERT INTO teams (name, coach) VALUES ('team64', 'coach64');
INSERT INTO teams (name, coach) VALUES ('team65', 'coach65');
INSERT INTO teams (name, coach) VALUES ('team66', 'coach66');
INSERT INTO teams (name, coach) VALUES ('team67', 'coach67');
INSERT INTO teams (name, coach) VALUES ('team68', 'coach68');
INSERT INTO teams (name, coach) VALUES ('team69', 'coach69');
INSERT INTO teams (name, coach) VALUES ('team70', 'coach70');
INSERT INTO teams (name, coach) VALUES ('team71', 'coach71');
INSERT INTO teams (name, coach) VALUES ('team72', 'coach72');
INSERT INTO teams (name, coach) VALUES ('team73', 'coach73');
INSERT INTO teams (name, coach) VALUES ('team74', 'coach74');
INSERT INTO teams (name, coach) VALUES ('team75', 'coach75');
INSERT INTO teams (name, coach) VALUES ('team76', 'coach76');
INSERT INTO teams (name, coach) VALUES ('team77', 'coach77');
INSERT INTO teams (name, coach) VALUES ('team78', 'coach78');
INSERT INTO teams (name, coach) VALUES ('team79', 'coach79');
INSERT INTO teams (name, coach) VALUES ('team80', 'coach80');
INSERT INTO teams (name, coach) VALUES ('team81', 'coach81');
INSERT INTO teams (name, coach) VALUES ('team82', 'coach82');
INSERT INTO teams (name, coach) VALUES ('team83', 'coach83');
INSERT INTO teams (name, coach) VALUES ('team84', 'coach84');
INSERT INTO teams (name, coach) VALUES ('team85', 'coach85');
INSERT INTO teams (name, coach) VALUES ('team86', 'coach86');
INSERT INTO teams (name, coach) VALUES ('team87', 'coach87');
INSERT INTO teams (name, coach) VALUES ('team88', 'coach88');
INSERT INTO teams (name, coach) VALUES ('team89', 'coach89');
INSERT INTO teams (name, coach) VALUES ('team90', 'coach90');
INSERT INTO teams (name, coach) VALUES ('team91', 'coach91');
INSERT INTO teams (name, coach) VALUES ('team92', 'coach92');
INSERT INTO teams (name, coach) VALUES ('team93', 'coach93');
INSERT INTO teams (name, coach) VALUES ('team94', 'coach94');
INSERT INTO teams (name, coach) VALUES ('team95', 'coach95');
INSERT INTO teams (name, coach) VALUES ('team96', 'coach96');
INSERT INTO teams (name, coach) VALUES ('team97', 'coach97');
INSERT INTO teams (name, coach) VALUES ('team98', 'coach98');
INSERT INTO teams (name, coach) VALUES ('team99', 'coach99');
INSERT INTO teams (name, coach) VALUES ('team100', 'coach100');
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team24', 'team54', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team74', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team98', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team56', 'team85', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team33', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team15', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team1', 'team76', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team54', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team14', 'team24', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team94', 'team20', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team80', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team43', 'team76', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team63', 'team27', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team61', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team13', 'team82', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team41', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team81', 'team41', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team63', 'team11', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team58', 'team51', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team43', 'team93', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team85', 'team87', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team90', 'team29', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team1', 'team95', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team72', 'team94', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team34', 'team29', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team12', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team14', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team23', 'team92', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team13', 'team7', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team84', 'team32', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team13', 'team3', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team52', 'team12', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team42', 'team21', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team50', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team78', 'team29', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team7', 'team23', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team66', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team26', 'team87', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team84', 'team90', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team86', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team13', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team97', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team96', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team23', 'team38', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team94', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team95', 'team91', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team86', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team18', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team54', 'team43', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team63', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team38', 'team40', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team5', 'team56', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team37', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team14', 'team86', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team41', 'team83', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team1', 'team67', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team27', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team50', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team56', 'team55', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team65', 'team53', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team89', 'team59', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team33', 'team72', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team89', 'team24', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team19', 'team72', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team10', 'team37', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team17', 'team16', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team47', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team98', 'team10', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team39', 'team52', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team84', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team77', 'team30', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team10', 'team51', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team26', 'team13', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team43', 'team96', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team41', 'team23', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team42', 'team47', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team76', 'team21', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team82', 'team75', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team95', 'team49', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team44', 'team37', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team34', 'team22', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team38', 'team83', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team82', 'team85', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team78', 'team12', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team66', 'team87', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team65', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team91', 'team55', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team13', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team4', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team90', 'team82', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team7', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team27', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team20', 'team36', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team17', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team7', 'team69', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team89', 'team21', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team74', 'team72', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team20', 'team86', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team30', 'team50', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team3', 'team12', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team64', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team3', 'team24', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team5', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team91', 'team40', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team43', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team22', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team9', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team38', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team70', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team78', 'team74', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team50', 'team98', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team5', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team9', 'team70', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team17', 'team19', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team67', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team78', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team34', 'team14', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team19', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team74', 'team25', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team53', 'team48', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team90', 'team28', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team74', 'team10', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team67', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team34', 'team19', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team77', 'team7', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team94', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team39', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team58', 'team68', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team79', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team63', 'team7', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team59', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team70', 'team42', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team30', 'team67', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team42', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team54', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team33', 'team78', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team40', 'team85', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team37', 'team7', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team54', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team44', 'team91', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team94', 'team81', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team20', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team9', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team82', 'team35', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team50', 'team80', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team17', 'team68', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team48', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team73', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team47', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team53', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team1', 'team90', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team41', 'team72', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team82', 'team96', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team29', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team65', 'team30', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team18', 'team6', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team68', 'team33', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team39', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team18', 'team58', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team56', 'team59', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team96', 'team36', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team42', 'team56', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team5', 'team17', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team43', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team91', 'team10', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team89', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team18', 'team41', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team95', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team39', 'team40', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team78', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team19', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team46', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team6', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team67', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team54', 'team80', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team73', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team81', 'team43', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team50', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team38', 'team53', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team12', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team16', 'team67', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team47', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team85', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team28', 'team89', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team63', 'team37', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team21', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team67', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team99', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team74', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team36', 'team91', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team94', 'team90', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team81', 'team39', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team66', 'team31', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team42', 'team59', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team16', 'team97', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team16', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team64', 'team57', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team56', 'team57', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team1', 'team61', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team77', 'team18', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team7', 'team65', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team99', 'team70', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team44', 'team10', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team98', 'team17', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team28', 'team25', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team89', 'team87', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team44', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team73', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team39', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team44', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team40', 'team99', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team16', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team20', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team74', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team74', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team21', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team20', 'team45', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team84', 'team49', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team66', 'team56', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team28', 'team3', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team36', 'team32', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team79', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team95', 'team5', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team17', 'team98', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team36', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team92', 'team25', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team28', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team75', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team69', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team10', 'team23', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team27', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team24', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team1', 'team59', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team82', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team22', 'team45', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team51', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team38', 'team6', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team47', 'team26', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team30', 'team24', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team46', 'team73', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team45', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team98', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team96', 'team8', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team46', 'team58', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team79', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team82', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team84', 'team99', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team66', 'team8', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team44', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team9', 'team46', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team13', 'team80', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team63', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team25', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team43', 'team91', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team100', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team13', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team28', 'team76', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team98', 'team72', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team73', 'team97', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team20', 'team89', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team24', 'team66', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team47', 'team30', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team44', 'team41', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team22', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team52', 'team63', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team72', 'team39', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team5', 'team63', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team77', 'team75', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team52', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team78', 'team34', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team98', 'team29', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team44', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team26', 'team40', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team1', 'team4', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team35', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team37', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team44', 'team81', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team92', 'team96', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team32', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team76', 'team4', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team62', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team24', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team31', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team11', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team26', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team9', 'team30', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team68', 'team66', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team20', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team2', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team53', 'team43', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team33', 'team3', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team20', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team39', 'team82', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team37', 'team81', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team29', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team58', 'team95', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team85', 'team21', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team43', 'team88', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team10', 'team22', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team20', 'team7', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team44', 'team96', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team92', 'team75', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team1', 'team56', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team65', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team33', 'team100', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team45', 'team65', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team47', 'team41', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team79', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team52', 'team22', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team18', 'team37', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team95', 'team21', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team100', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team81', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team46', 'team75', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team52', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team15', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team50', 'team77', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team3', 'team82', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team25', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team23', 'team63', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team82', 'team46', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team56', 'team20', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team85', 'team71', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team33', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team3', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team43', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team76', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team99', 'team20', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team18', 'team66', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team16', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team14', 'team27', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team21', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team95', 'team51', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team72', 'team6', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team26', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team41', 'team63', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team13', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team29', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team73', 'team83', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team68', 'team93', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team71', 'team62', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team95', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team14', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team44', 'team18', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team16', 'team9', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team58', 'team81', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team40', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team71', 'team13', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team47', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team54', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team90', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team81', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team80', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team16', 'team66', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team47', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team60', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team63', 'team84', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team92', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team89', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team76', 'team85', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team53', 'team17', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team26', 'team43', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team70', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team18', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team45', 'team14', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team96', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team94', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team99', 'team5', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team79', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team42', 'team93', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team26', 'team65', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team80', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team34', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team96', 'team53', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team100', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team17', 'team27', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team28', 'team22', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team41', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team94', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team32', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team67', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team62', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team96', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team29', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team72', 'team13', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team50', 'team81', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team22', 'team51', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team66', 'team6', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team7', 'team22', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team79', 'team66', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team41', 'team19', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team74', 'team76', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team50', 'team8', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team64', 'team27', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team23', 'team7', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team64', 'team5', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team45', 'team5', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team32', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team50', 'team23', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team61', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team63', 'team15', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team62', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team41', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team55', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team98', 'team32', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team42', 'team43', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team81', 'team30', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team82', 'team55', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team90', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team80', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team64', 'team59', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team50', 'team59', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team70', 'team45', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team13', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team64', 'team20', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team3', 'team16', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team53', 'team25', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team72', 'team48', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team30', 'team80', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team19', 'team36', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team1', 'team83', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team14', 'team5', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team71', 'team22', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team92', 'team77', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team99', 'team67', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team37', 'team93', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team71', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team2', 'team15', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team40', 'team52', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team85', 'team23', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team19', 'team39', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team24', 'team23', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team99', 'team12', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team73', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team78', 'team93', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team39', 'team72', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team54', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team64', 'team92', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team72', 'team56', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team70', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team66', 'team28', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team97', 'team31', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team83', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team84', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team58', 'team100', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team45', 'team27', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team27', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team46', 'team98', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team10', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team22', 'team20', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team84', 'team17', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team81', 'team26', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team21', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team27', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team37', 'team67', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team46', 'team94', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team9', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team6', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team99', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team17', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team54', 'team26', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team47', 'team81', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team48', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team49', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team10', 'team91', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team70', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team67', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team40', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team40', 'team75', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team33', 'team30', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team46', 'team45', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team94', 'team96', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team77', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team71', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team5', 'team60', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team12', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team7', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team9', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team43', 'team27', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team83', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team41', 'team82', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team95', 'team20', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team27', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team81', 'team79', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team23', 'team100', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team56', 'team90', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team64', 'team14', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team71', 'team90', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team33', 'team14', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team23', 'team66', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team99', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team68', 'team88', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team91', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team2', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team68', 'team20', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team20', 'team83', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team13', 'team8', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team33', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team59', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team82', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team36', 'team34', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team76', 'team57', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team42', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team37', 'team30', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team8', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team47', 'team61', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team18', 'team62', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team45', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team97', 'team43', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team72', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team58', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team39', 'team84', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team91', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team10', 'team68', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team77', 'team28', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team92', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team26', 'team38', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team5', 'team92', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team99', 'team89', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team14', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team56', 'team74', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team44', 'team6', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team95', 'team44', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team29', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team53', 'team83', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team40', 'team50', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team67', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team29', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team63', 'team40', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team26', 'team96', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team38', 'team54', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team36', 'team25', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team95', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team22', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team71', 'team51', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team77', 'team42', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team66', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team29', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team81', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team76', 'team99', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team84', 'team68', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team53', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team39', 'team26', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team65', 'team94', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team78', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team40', 'team72', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team77', 'team52', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team44', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team89', 'team64', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team42', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team66', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team51', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team55', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team46', 'team62', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team94', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team38', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team53', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team66', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team10', 'team65', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team42', 'team98', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team37', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team35', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team24', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team76', 'team86', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team22', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team70', 'team98', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team97', 'team46', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team24', 'team94', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team76', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team75', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team98', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team91', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team78', 'team91', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team80', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team3', 'team17', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team64', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team19', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team59', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team26', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team94', 'team69', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team64', 'team51', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team73', 'team42', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team89', 'team88', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team54', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team30', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team1', 'team33', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team92', 'team23', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team38', 'team45', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team12', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team19', 'team10', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team94', 'team43', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team54', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team63', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team82', 'team70', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team8', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team78', 'team4', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team53', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team68', 'team61', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team80', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team2', 'team27', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team17', 'team53', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team5', 'team57', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team4', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team14', 'team61', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team5', 'team89', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team16', 'team43', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team14', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team64', 'team79', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team69', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team95', 'team54', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team53', 'team14', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team33', 'team66', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team53', 'team61', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team74', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team74', 'team90', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team45', 'team39', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team2', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team55', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team26', 'team2', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team13', 'team73', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team45', 'team83', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team78', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team4', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team33', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team74', 'team55', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team7', 'team74', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team99', 'team62', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team82', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team65', 'team46', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team41', 'team7', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team82', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team65', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team3', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team30', 'team52', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team43', 'team71', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team56', 'team84', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team7', 'team92', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team43', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team39', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team34', 'team77', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team42', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team86', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team97', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team92', 'team97', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team36', 'team20', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team47', 'team21', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team49', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team40', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team9', 'team54', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team44', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team72', 'team65', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team14', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team79', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team77', 'team72', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team29', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team55', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team60', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team66', 'team38', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team63', 'team41', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team22', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team89', 'team60', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team9', 'team94', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team45', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team68', 'team67', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team36', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team36', 'team59', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team76', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team72', 'team44', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team78', 'team73', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team54', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team71', 'team91', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team34', 'team80', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team5', 'team3', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team78', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team90', 'team10', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team40', 'team28', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team58', 'team1', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team76', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team69', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team20', 'team26', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team91', 'team33', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team66', 'team5', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team20', 'team3', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team39', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team96', 'team70', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team19', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team36', 'team96', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team42', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team78', 'team88', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team23', 'team80', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team82', 'team66', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team90', 'team83', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team93', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team22', 'team29', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team75', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team18', 'team19', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team36', 'team52', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team57', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team46', 'team10', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team37', 'team51', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team11', 'team8', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team18', 'team31', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team94', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team50', 'team24', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team7', 'team39', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team96', 'team56', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team98', 'team40', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team47', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team39', 'team8', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team86', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team12', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team76', 'team62', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team54', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team79', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team23', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team79', 'team44', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team60', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team96', 'team26', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team35', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team78', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team96', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team50', 'team53', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team14', 'team91', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team58', 'team87', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team2', 'team35', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team54', 'team78', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team29', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team90', 'team24', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team65', 'team21', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team25', 'team34', 5, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team82', 'team54', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team40', 'team95', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team10', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team66', 'team42', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team61', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team2', 'team71', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team56', 'team34', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team14', 'team7', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team5', 'team18', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team72', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team70', 'team19', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team7', 'team99', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team58', 'team65', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team89', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team65', 'team43', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team81', 'team20', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team91', 'team65', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team81', 'team96', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team100', 'team32', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team65', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team100', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team22', 'team99', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team61', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team72', 'team52', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team50', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team88', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team72', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team58', 'team78', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team61', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team97', 'team87', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team20', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team3', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team36', 'team2', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team92', 'team70', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team95', 'team31', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team51', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team85', 1, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team77', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team98', 'team89', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team76', 'team24', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team79', 'team64', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team37', 'team66', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team5', 'team66', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team2', 'team52', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team68', 'team45', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team51', 'team64', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team66', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team16', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team50', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team18', 'team33', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team57', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team82', 'team100', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team2', 'team23', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team14', 'team81', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team93', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team7', 'team14', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team33', 'team70', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team44', 'team13', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team53', 'team19', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team80', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team31', 'team64', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team37', 'team28', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team41', 'team85', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team26', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team17', 'team12', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team93', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team59', 'team38', 3, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team97', 'team13', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team7', 'team8', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team23', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team53', 'team82', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team79', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team62', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team36', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team76', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team50', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team13', 'team46', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team37', 'team45', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team41', 'team60', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team52', 'team58', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team68', 'team83', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team53', 'team44', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team70', 'team69', 4, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team94', 'team88', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team91', 'team77', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team52', 'team88', 2, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team70', 'team40', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team30', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team39', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team93', 'team71', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team52', 'team26', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team84', 'team43', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team28', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team34', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team63', 'team78', 4, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team34', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team78', 'team11', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team19', 'team75', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team76', 'team79', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team4', 'team35', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team96', 'team48', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team36', 'team56', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team80', 'team72', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team56', 'team9', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team80', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team76', 'team81', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team72', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team9', 'team73', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team74', 'team39', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team85', 'team34', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team46', 'team37', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team40', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team27', 'team57', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team65', 'team61', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team6', 'team68', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team14', 'team73', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team55', 'team24', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team21', 'team34', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team87', 'team80', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team9', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team3', 'team76', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team98', 'team21', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team70', 'team75', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team10', 'team92', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team38', 4, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team3', 'team47', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team13', 'team51', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team40', 'team38', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team23', 'team13', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team85', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team21', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team58', 'team31', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team86', 'team23', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team44', 'team79', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team72', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team97', 'team30', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team92', 'team49', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team76', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team94', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team8', 'team21', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team72', 'team31', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team89', 'team15', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team30', 'team32', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team34', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team85', 'team33', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team70', 'team38', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team17', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team48', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team20', 'team2', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team30', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team83', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team63', 'team80', 0, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team15', 'team28', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team60', 'team3', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team72', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team92', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team88', 'team47', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team74', 'team70', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team92', 'team46', 3, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team20', 'team25', 1, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team73', 'team38', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team41', 'team55', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team90', 'team84', 0, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team54', 'team65', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team30', 'team83', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team45', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team23', 'team31', 4, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team70', 'team66', 2, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team29', 'team92', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team39', 0, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team35', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team79', 'team45', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team34', 'team49', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team12', 'team85', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team91', 1, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team75', 'team38', 1, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team83', 'team59', 4, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team69', 'team37', 3, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team61', 'team7', 2, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team42', 'team73', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team39', 'team7', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team77', 'team40', 2, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team45', 1, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team96', 'team6', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team67', 'team5', 4, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team47', 'team80', 5, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team35', 'team91', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team68', 'team7', 5, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team57', 'team1', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team37', 'team75', 3, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team49', 'team77', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team48', 'team23', 0, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team33', 'team59', 0, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team16', 'team51', 2, 1);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team34', 'team48', 3, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team64', 'team22', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team94', 'team1', 2, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team89', 'team18', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team40', 'team46', 5, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team94', 'team97', 0, 3);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team98', 'team86', 5, 4);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team2', 'team33', 3, 2);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team85', 'team90', 5, 5);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team32', 'team29', 1, 0);
INSERT INTO matches (hTeam, vTeam, hScore, vScore) VALUES ('team62', 'team84', 5, 0);
